# Generated by Django 6.1 on 2026-08-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True)),
                ('ip_hash', models.CharField(max_length=64)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('referer_domain', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='links.link')),
            ],
            options={
                'indexes': [models.Index(fields=['link', '-created_at'], name='links_click_link_id_9493ed_idx')],
            },
        ),
    ]
