# Generated by Django 6.0.8 on 2026-08-18 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_clickevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_visitors', models.PositiveIntegerField(default=0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='links.link')),
            ],
            options={
                'indexes': [models.Index(fields=['link', '-date'], name='links_daily_link_id_3aa605_idx')],
                'constraints': [models.UniqueConstraint(fields=('link', 'date'), name='uniq_link_date')],
            },
        ),
    ]
